version: '2.1'
services:
  api:
    image: api
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: mysqladmin ping -h ${DB_HOST} -u ${DB_USERNAME} --password=${DB_PASSWORD}
      interval: 20s
      timeout: 10s
      retries: 5